package uiak.exper.gisamt.model;

public enum AppComponentType {
	UI_SERVER, SERVICE_SERVER, BATCH, INTEGRATION, ASYNC, DATA_LOAD, DATA_EXTRACT, CALC_ENGINE, FILE_SHARE, SMART_CLIENT, ASP_BROWSER, ASP_DESKTOP, SCHEDULER
}
